version: '3.8'
services:
  db:
    image: postgres:15.2
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 5435:5436
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_admin=admin
    networks:
      - default_network
volumes:
  db-store:
networks:
  default_network:
